#!/bin/bash
# Nek5000 build config file

function error_quit {
    echo -e "$@"
    echo
    echo -e 'Usage:'
    echo -e './compile_script [--solver drl|raw] --clean'
    echo -e './compile_script [--solver drl|raw] --all'
    exit 1
}

export CASE="small_wing"
# `raw` selects the unpatched Nek5000 core and writes nek5000_solo, the
# executable used by the embedded Python-free controller.
SOLVER="drl"
POSARGS=()
while [[ $# -gt 0 ]]; do
    case $1 in
        --solver) SOLVER="$2"; shift 2 ;;
        *) POSARGS+=("$1"); shift ;;
    esac
done
set -- "${POSARGS[@]}"

case ${SOLVER} in
    drl) SOLVER_ROOT="DEC_DRL_Nek5000"; BINNAME="nek5000" ;;
    raw) SOLVER_ROOT="DEC_Nek5000";     BINNAME="nek5000_solo" ;;
    *)   error_quit "Unknown --solver '${SOLVER}', expected drl or raw." ;;
esac
export MAKEFLAGS="BINNAME=${BINNAME} LIBNAME=lib${BINNAME}.a"

## LOCAL ------------------
# source path
SOURCE_ROOT="../../solver/${SOLVER_ROOT}"
# Fortran compiler
F77="mpif77"
# C compiler
CC="mpicc"
## ------------------------

# source path
#SOURCE_ROOT="/cfs/klemming/nobackup/a/atzori/DEC_Nek5000"
# Fortran compiler
#F77="ftn"
# C compiler
#CC="cc"
#CC="cc -D_Float128=__float128"

SOURCE_ROOT_CORE="$SOURCE_ROOT/core"
SOURCE_ROOT_JL="$SOURCE_ROOT/jl"
SOURCE_ROOT_CMT="$SOURCE_ROOT/core/cmt"


# OPTIONAL SETTINGS
# -----------------

# generic compiler flags
#G="-g"
G="-I./inc_src -mcmodel=large -std=legacy"
# G="-I./inc_src -std=legacy"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
# PPLIST="MPIIO" 
PPLIST="MPIIO DRL YWDEBUG UTAU NETGAIN"

# linking flags
#USR_LFLAGS="-L/usr/lib -lfoo"

# enable MPI (default true)
#IFMPI="false"

# disable/enable profiling (default true`)
IFPROFILING="true"

# enable AMG coarse grid solver (default XXT)
#IFAMG="true"
#IFAMG_DUMP="true"

# optimization flags
#OPT_FLAGS_STD=""
#OPT_FLAGS_MAG=""

# enable CMT (default false)
#IFCMT="true"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"
USR="IO_tools.o chkpoint.o uparam.o"
## Statistics
USR+=" statistics_2D.o statistics_2DIO.o statistics_2D_usr.o statistics_2D_debug.o"
## Time-series
USR+=" time_series.o time_seriesIO.o pts_redistribute.o err_est.o"
## Tripping force
USR+=" rt_filter.o tripf.o misc.o"
## CTRL
# USR+=" oppo_ctrl.o oppo_ctrl_IO.o"
USR+=" drl_main.o drl_action.o drl_init.o drl_reward.o drl_state.o drl_IO.o"
USR+=" pol_core.o pol_net.o pol_main.o pol_IO.o pol_action.o"


# MOAB/iMESH path
#MOAB_DIR="$HOME/moab"

# For linking to MOAB, the following might be needed:
# NOTE: compiler specific, use the appropriate one depending on your compiler
# GNU:
# USR_LFLAGS="-lmpi_cxx -lstdc++"
# Intel:
# USR_LFLAGS="-cxxlib"
# PGI:
# USR_LFLAGS="-pgcpplibs"
# USR_LFLAGS=" -lmpi_cxx -lstdc++"

# enable VisIt in situ
#  Note: you can override the lib and include paths. VISIT_LIB and VISIT_INC
#  If VISIT_STOP is set the simulation will stop after first step and wait
#  for VisIt to connect.
#IFVISIT=true
#VISIT_INSTALL="/path/to/visit/current/linux-x86_64/"
#VISIT_STOP=true

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
if [ $# -ne 1 ]; then
  error_quit 'Wrong arguments number!'
fi

case $1 in
  --clean)
    set -- clean
    source "$SOURCE_ROOT_CORE/makenek.inc"
    ;;
  --all)
    set -- "${CASE}"
    source "$SOURCE_ROOT_CORE/makenek.inc"
    make -j4 -f makefile ${MAKEFLAGS} 2>&1 | tee log_compile.out
    ;;
  *)
    error_quit 'Wrong argument.'
    ;;
esac
