#!/bin/bash -l

repo="kth"

# repo="julich"

branchName="dev_yw_fxb"

# repo='juwels'
# branchName='yw_local_dev'

commitMessage="Update"  # Default commit message
# Parse arguments for commit message
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --m) commitMessage="$2"; shift ;; # Set commit message
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

echo "====================================="
echo "           GITHUB UPDATE              "
echo "====================================="

git add . 

git commit -m"${commitMessage}"

git push --force "$repo" "$branchName" 

echo "====================================="
echo "           FINISHED!                 "
echo "====================================="
echo "PUSH BRANCH: $branchName TO $repo"
